### ISSUE TITLE
Include outer library if somebody has implemented.

### ISSUE THREAD

**Issue by dylandy** [ruivieira/crystal-gsl#20]
such as Matrix : https://github.com/Exilor/matrix

**Comment by ruivieira** [comment]
Hi @dylandy,

Regarding _direct_ inclusion, I'm not totally in favour, for the following reasons:

1. `matrix` is pure Crystal AFAIK, and `crystal-gsl` is supposed to be a binding to `GSL`
2. `matrix` is actually less-performant than the _extensively_ tested and optimised `GSL`, in a (very) simple multiplication benchmark I did with large matrices, this was the results:

```
GSL   8.77k (113.97µs) (±10.62%)       fastest
Exilor 685.22  (  1.46ms) (± 2.93%) 12.81× slower
```

*However*, I do agree that `matrix` has a nice API/interface, and I wouldn't mind using it, especially because:

1. If the API is more or less uniform, users can less painfully switch libraries if they want
2. Although this is a binding to `GSL`, it's supposed to be idiomatic Crystal, so I'm not fussy about the API.

So I'm closing with a `wontfix`, but PR for a more `matrix` like API to `GSL` are welcome!

Thanks!
